name: Optimize resource pack

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = './pack.zip'

      - name: Generate hash
        shell: bash
        run: |
          HASH=$(sha1sum pack.zip | cut -d ' ' -f 1)
          echo -n "$HASH" > hash.txt
          cp pack.zip "$HASH.zip"

      - name: Remove old latest release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag --yes || true

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Resource Pack
          make_latest: true
          files: |
            pack.zip
            hash.txt
            [a-f0-9]*.zip
